title       = "dantri"
baseURL     = "https://dantri-cli.tamnd.com/"
description = "A command line for dantri."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/dantri-cli"
